In [25]:
import numpy as np

In [27]:
a=np.random.randint(30,99,(7,8))
a

array([[74, 54, 90, 76, 86, 64, 96, 49],
       [30, 51, 94, 63, 64, 90, 58, 42],
       [96, 67, 93, 81, 59, 43, 89, 77],
       [68, 45, 55, 76, 74, 91, 54, 93],
       [76, 63, 52, 71, 94, 80, 94, 83],
       [90, 78, 95, 43, 85, 66, 54, 85],
       [72, 87, 74, 55, 40, 66, 35, 95]])

In [127]:
b=np.random.randint(20,80,(8,9))
b

array([[55, 30, 50, 74, 44, 41, 51, 74, 43],
       [50, 21, 50, 73, 57, 66, 65, 60, 67],
       [74, 32, 46, 34, 78, 62, 34, 68, 70],
       [49, 63, 34, 24, 46, 67, 77, 21, 39],
       [49, 57, 51, 61, 53, 34, 51, 36, 52],
       [60, 50, 24, 70, 42, 62, 61, 74, 43],
       [77, 23, 29, 45, 20, 31, 54, 78, 69],
       [56, 20, 25, 72, 67, 39, 21, 34, 50]])

In [57]:
b.shape

(8, 9)

In [129]:
b[1:5]

array([[50, 21, 50, 73, 57, 66, 65, 60, 67],
       [74, 32, 46, 34, 78, 62, 34, 68, 70],
       [49, 63, 34, 24, 46, 67, 77, 21, 39],
       [49, 57, 51, 61, 53, 34, 51, 36, 52]])

In [131]:
b[1:5,1:6]

array([[21, 50, 73, 57, 66],
       [32, 46, 34, 78, 62],
       [63, 34, 24, 46, 67],
       [57, 51, 61, 53, 34]])

In [192]:
b[1:2:6,1:7:2]

array([[21, 73, 66]])

In [ ]:
array[row_start: row_end : row_step , col_start: col_end:col_step

In [151]:
import pandas as pd

In [200]:
k=[[4,7],[2,9],[7,3],[90,50]]
k

[[4, 7], [2, 9], [7, 3], [90, 50]]

In [202]:
t=np.array(k)
t

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

In [204]:
t.ndim

2

In [208]:
pd.Series(t)

ValueError: Data must be 1-dimensional, got ndarray of shape (4, 2) instead

In [210]:
t

array([[ 4,  7],
       [ 2,  9],
       [ 7,  3],
       [90, 50]])

In [214]:
pd.DataFrame(t)

0   1
0   4   7
1   2   9
2   7   3
3  90  50

In [222]:
df=pd.DataFrame(t,columns=['name','sub'],index=[289,290,291,292,])
df

name  sub
289     4    7
290     2    9
291     7    3
292    90   50

In [224]:
df.columns

Index(['name', 'sub'], dtype='object')

In [246]:
df['sub']

289     7
290     9
291     3
292    50
Name: sub, dtype: int32

In [248]:
df['sub'].mean()

17.25

In [230]:
df.sub

<bound method DataFrame.sub of      name  sub
289     4    7
290     2    9
291     7    3
292    90   50>

In [250]:
df['sub'].var()

482.9166666666667

In [252]:
df['sub'].std()

21.975364995072702

In [254]:
df['sub'].min()

3

In [256]:
df['sub'].max()

50

In [258]:
df['sub'].quantile(0.25)

6.0

In [260]:
df['sub'].quantile(0.75)

19.25

In [262]:
df['sub'].quantile(0.90)

37.7